# Generated by Django 5.2 on 2025-05-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matching',
            name='status',
            field=models.CharField(choices=[('pending', '대기중'), ('matching', '매칭됨')], default='pending', max_length=10),
        ),
    ]
