# Generated by Django 5.2 on 2025-05-19 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_matching_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='students',
        ),
    ]
