# Generated by Django 5.2 on 2025-05-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_student_teacher'),
        ('teacher', '0003_remove_problem_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
    ]
