# Generated by Django 5.2 on 2025-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_problem_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='submits',
            field=models.TextField(null=True),
        ),
    ]
