# Generated by Django 5.2 on 2025-05-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_problem_submits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='students',
        ),
    ]
