# Generated by Django 5.2 on 2025-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_problem_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
