# Generated by Django 5.2 on 2025-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cassuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassuser',
            name='role',
            field=models.CharField(choices=[('teacher', '선생'), ('student', '학생')], max_length=10, verbose_name='역할'),
        ),
    ]
